# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  imageName : 'tobpro87/calculator'
  containerRegistry : 'tobpro87.hub.docker.com'

steps:
# - task: Docker@2
#   inputs:
#     containerRegistry: 'tobpro87.hub.docker.com'
#     repository: tobpro87/calculator
#     command: 'buildAndPush'
#     Dockerfile: '**/Dockerfile'
- task: CMake@1
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  inputs:
    cmakeArgs: '--build .'
- task: CMake@1
  inputs:
    cmakeArgs: '--build . --target BUILD_TEST'
- task: PublishTestResults@2
  inputs:
    testResultsFormat: 'CTest'
    testResultsFiles: '**/TEST.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/build/Testing'