# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

variables:
  imageName : 'tobpro87/calculator'
  containerRegistry : 'tobpro87.hub.docker.com'

steps:
- task: Docker@2
  inputs:
    containerRegistry: 'tobpro87.hub.docker.com'
    command: 'build'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'tobpro87.hub.docker.com'
    repository: 'calculator'
    command: 'push'
- task: CMake@1
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  inputs:
    cmakeArgs: '--build .'
