# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- develop

pool:
  vmImage: ubuntu-latest

steps:
- task: docker@2
  inputs:
    repository: calculator
    command: build
    dockerfile: Dockerfile
  displayName: Build image
- task: Docker@2
  inputs:
    containerRegistry: |
      tobpro87.hub.docker.com
    repository: $(imageName)
    command: push
    tags: |
      test1
      test2
  displayName: Push image
- task: CMake@1
  inputs:
    cmakeArgs: '..'
- task: CMake@1
  inputs:
    cmakeArgs: '--build .'
